import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "../../pages/components/header";
import Footer from "../../pages/components/footer";
import Head from 'next/head';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html>
      <body>
      <Head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" />
      </Head>
      <div className="root-layout">
        <Header />
        {children}
        <Footer />
      </div>
      </body>
      </html>
    </>
  );
}
